### ISSUE TITLE
Upgrade mismatch with current DBT core release

### ISSUE THREAD

**Issue by modernShane** [duckdb/dbt-duckdb#485]
Running a pip upgrade on a DBT environment seems to be failing a compatibility test.  My personal build doesn't seem to be affected by whatever compatibility mismatch there may be, but I wanted to raise it in case it was going to be impactful for others.  Again, my environment and project are running fine, so I don't have any further logs or symptoms.

dbt --version
Core:
  - installed: 1.8.9
  - latest:    1.8.9 - Up to date!

Plugins:
  - duckdb: 1.9.0 - Not compatible!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

**Comment by jwills** [comment]
Yeah, this seems like an unfortunate side effect of dbt-core not having a regular 1.9.0 release out the door yet, even though we are primarily building dbt-duckdb against it now-- @dbeatty10 curious if you have any thoughts here-- is this situation fine, should we fix something, should you fix something, etc., etc.

**Comment by dbeatty10** [comment]
@jwills my initial thought is that this is something to address within `dbt-core` rather than something to address in `dbt-duckdb`.

i.e., this looks like the issue raised in https://github.com/dbt-labs/dbt-core/issues/10230, so I think you could safely close https://github.com/duckdb/dbt-duckdb/issues/485 in favor of that one.

I think this is how we could solve it in `dbt-core`: https://github.com/dbt-labs/dbt-core/issues/10230#issuecomment-2134343235

**Comment by jwills** [comment]
Excellent @dbeatty10 -- thank you as always!

**Comment by jwills** [comment]
Closing this in favor of the fix for this issue in dbt-core: https://github.com/dbt-labs/dbt-core/issues/10230
